### ISSUE TITLE
Enable multiple variable=val1,val2,... for a single output block

### ISSUE THREAD

**Issue by felker** [PrincetonUniversity/athena#246]
**Is your feature request related to a problem? Please describe.**
I just added `b` to the available `variable` choices for `<output[n]>` blocks in the in put files (1dc5b1a3e0c86621dba3c001026df9d330fa9815). I usually only output `prim` or `cons`, so I had no idea that it is not possible to have:
```
<output3>
file_type   = tab      
variable    = b, prim
data_format = %24.16e
dt          = 0.000001 
ghost_zones = true
```
But instead you must have separate `<output[n]>` blocks and hence separate `.tab`, etc. output files:
```
<output3>
file_type   = tab      
variable    = b
data_format = %24.16e
dt          = 0.000001 
ghost_zones = true

<output4>
file_type   = tab      
variable    = prim
data_format = %24.16e
dt          = 0.000001 
ghost_zones = true
```
This is obviously inconvenient and wasteful due to redundant outputs.

**Describe the solution you'd like**
It would be straightforward to make the comma-separated (w/ or w/o whitespace), multiple value `variable` possible with the existing infrastructure in `outputs/`. 

Would this be useful to others?

Other suggestions:
- [ ] Make the possible values case insensitive, e.g. `bcc` and `Bcc`. Except for `d` and `D`, which represent different quantities (unless we rename them). 
- [ ] Make `cons` include `b` output instead of `bcc` (since the face fields, not the cell-centered fields, form the primary representation of the magnetic fields)

**Comment by haoenz** [comment]
The wiki already claims it can do this
> To select multiple variables, a list of variables separated by a single comma `,` should be provided (e.g., to select conservative density and pressure, use `D,p`). 

But this feature does not appear to be implemented yet ?
