### ISSUE TITLE
Potentially Ill-Defined Ambipolar Diffusion Constant Diffusivity

### ISSUE THREAD

**Issue by pdmullen** [PrincetonUniversity/athena#369]
**Summary of issue**

In Equation 6d of the Athena++ code paper  (https://arxiv.org/abs/2005.06651), the induction equation is given as

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{\partial&space;\mathbf{B}}{\partial&space;t}&space;-&space;\nabla&space;\times&space;\left[\left(\mathbf{v}&space;\times&space;\mathbf{B}&space;\right)&space;-&space;\eta&space;\mathbf{J}&space;-&space;\frac{\eta_\mathrm{AD}}{\lvert&space;\mathbf{B}&space;\rvert^2}&space;\mathbf{B}&space;\times&space;\left(\mathbf{J}&space;\times&space;\mathbf{B}&space;\right)&space;\right&space;]&space;=&space;0" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{\partial&space;\mathbf{B}}{\partial&space;t}&space;-&space;\nabla&space;\times&space;\left[\left(\mathbf{v}&space;\times&space;\mathbf{B}&space;\right)&space;-&space;\eta&space;\mathbf{J}&space;-&space;\frac{\eta_\mathrm{AD}}{\lvert&space;\mathbf{B}&space;\rvert^2}&space;\mathbf{B}&space;\times&space;\left(\mathbf{J}&space;\times&space;\mathbf{B}&space;\right)&space;\right&space;]&space;=&space;0" title="\frac{\partial \mathbf{B}}{\partial t} - \nabla \times \left[\left(\mathbf{v} \times \mathbf{B} \right) - \eta \mathbf{J} - \frac{\eta_\mathrm{AD}}{\lvert \mathbf{B} \rvert^2} \mathbf{B} \times \left(\mathbf{J} \times \mathbf{B} \right) \right ] = 0" /></a>

As presented, I believe <a href="https://www.codecogs.com/eqnedit.php?latex=\eta" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\eta" title="\eta" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\eta_\mathrm{AD}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\eta_\mathrm{AD}" title="\eta_\mathrm{AD}" /></a> should have units of [length]^2/[time].  In `ConstDiffusivity`, the input parameter `<problem>/eta_ad` is multiplied by <a href="https://www.codecogs.com/eqnedit.php?latex=\lvert&space;\mathbf{B}&space;\rvert^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\lvert&space;\mathbf{B}&space;\rvert^2" title="\lvert \mathbf{B} \rvert^2" /></a> :

https://github.com/PrincetonUniversity/athena/blob/accda406331e9d31dcc38da64745a61daef2a886/src/field/field_diffusion/diffusivity.cpp#L57-L58

This quantity `etaB(FieldDiffusion::DiffProcess::ambipolar,k,j,i)` is then used to compute the parabolic time step and the ambipolar EMF.  It therefore seems that there is an inconsistency between `eta_ad` and <a href="https://www.codecogs.com/eqnedit.php?latex=\eta_\mathrm{AD}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\eta_\mathrm{AD}" title="\eta_\mathrm{AD}" /></a> from the Athena++ code paper.  Can someone check my logic here?

I imagine that the factor of `SQR(bmag(k,j,i))` was multiplied to `eta_ad` because the ambipolar diffusion coefficient is typically <a href="https://www.codecogs.com/eqnedit.php?latex=\propto&space;\lvert&space;\mathbf{B}&space;\rvert^2" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\propto&space;\lvert&space;\mathbf{B}&space;\rvert^2" title="\propto \lvert \mathbf{B} \rvert^2" /></a>.  Following [Masson et al. 2012](https://arxiv.org/pdf/1206.2476.pdf), the ambipolar diffusion coefficient can be approximated as 

<a href="https://www.codecogs.com/eqnedit.php?latex=\eta_\mathrm{AD}&space;=&space;\frac{\lvert&space;\mathbf{B}&space;\rvert^2}{\rho&space;\:&space;\rho_i&space;\:&space;\gamma_\mathrm{AD}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\eta_\mathrm{AD}&space;=&space;\frac{\lvert&space;\mathbf{B}&space;\rvert^2}{\rho&space;\:&space;\rho_i&space;\:&space;\gamma_\mathrm{AD}}" title="\eta_\mathrm{AD} = \frac{\lvert \mathbf{B} \rvert^2}{\rho \: \rho_i \: \gamma_\mathrm{AD}}" /></a>

**Proposal:**
I propose that we:
(A) Let `eta_ad` = `etaB(FieldDiffusion::DiffProcess::ambipolar,k,j,i)` = <a href="https://www.codecogs.com/eqnedit.php?latex=\eta_\mathrm{AD}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\eta_\mathrm{AD}" title="\eta_\mathrm{AD}" /></a> from [Stone et al. 2020](https://arxiv.org/pdf/2005.06651.pdf) for the `ConstDiffusivity` case, by eliminating the factor of `SQR(bmag(k,j,i)`.  
(B) Leave the case of a spatially varying `etaB(FieldDiffusion::DiffProcess::ambipolar,k,j,i)` tasked to the user to define (by enrolling their own diffusion coefficient function).

If I make this change, then I can simply run the `resist.cpp` pgen, replacing `eta_ohm` with `eta_ad`, and diffuse a 1-D Gaussian <a href="https://www.codecogs.com/eqnedit.php?latex=B_y" target="_blank"><img src="https://latex.codecogs.com/gif.latex?B_y" title="B_y" /></a> distribution via ambipolar diffusion.  The resulting error convergence is shown here (alongside the Ohmic diffusion case).  

![l1_field_diffusion](https://user-images.githubusercontent.com/33095288/120041944-313eb880-bfd7-11eb-8444-b82ad9f8853f.png)

**Alternatives:**
(C) We can keep the present implementation and make an edit to the documentation so that the user has a better idea of what `eta_ad` really is.  
(D) We could actually define `eta_ad` = `pfdif->etaB(FieldDiffusion::DiffProcess::ambipolar, k,j,i) = pfdif->Q_AD*SQR(bmag(k,j,i))/w(IDN,k,j,i)` = <a href="https://www.codecogs.com/eqnedit.php?latex=\eta_\mathrm{AD}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\eta_\mathrm{AD}" title="\eta_\mathrm{AD}" /></a> from [Stone et al. 2020](https://arxiv.org/pdf/2005.06651.pdf) , as done here: https://github.com/PrincetonUniversity/Athena-Cversion/blob/bb328f4ac6fd2c5a2f1881b12fe5e356ed60849b/src/microphysics/get_eta.c#L110.  In this way, for example, the oblique C-shock problem with ambipolar diffusion (see [3.3.4](https://arxiv.org/pdf/2005.06651.pdf)) could be run *without* a user defined diffusivity, by simply setting `problem/Q_AD = 1./75.` (corresponding to <a href="https://www.codecogs.com/eqnedit.php?latex=\gamma_{AD}&space;=&space;75" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\gamma_{AD}&space;=&space;75" title="\gamma_{AD} = 75" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\rho_i&space;=&space;1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\rho_i&space;=&space;1" title="\rho_i = 1" /></a>).  Note that if we accept proposal (A), the oblique C-shock test could **not** be run unless a user-defined diffusivity is set.  
 
**Ideas for Future**
(1) If we accept my proposal (A), then for static meshes with a non-spatially varying, time-independent diffusivity, we do not need to recompute the diffusivities for every explicit integration stage (or STS stage).  Presently, even when using `ConstDiffusivity`, the diffusivities are always reset prior to computing fluxes.   By eliminating all these extra calls, we could improve performance.  
(2) By extension of (1), for static meshes with a non-spatially varying, time-independent diffusivity, we only need to compute the parabolic time-step once---at the beginning of the calculation! This could also enhance performance.
(3) Can we remove all Hall diffusion related code from Athena++ until Hall diffusion is actually implemented?

**Comment by felker** [comment]
@tomidakn and I vote A)

**Comment by felker** [comment]
@tomidakn @pdmullen I can't remember where we left off with this?

**Comment by pdmullen** [comment]
> @tomidakn @pdmullen I can't remember where we left off with this?

I will handle this. Sorry for the delay, busy times.

**Comment by zhuzh1983** [comment]
This implementation has been in the code for a while. Many people may have adopted this definition. If we change it now, it can cause confusion. I would suggest that we keep it as it is but just change the document. One benefit of using this is that, in the standard shearing box MRI simulations, eta_ad in the code is inverse proportional to the dimensionless Am without the presence of B^2.

**Comment by pdmullen** [comment]
I am open to this.  I also worry that changing this now may do more harm than good.  I think the change to the documentation should be something along the lines of:

`eta_ad` does *not* correspond to the ambipolar diffusion coefficient (i.e., it does *not* have units of [length]^2/[time]).  Rather, the product of `eta_ad` and the local magnetic field strength squared gives the ambipolar diffusion coefficient.  This product is computed via the code automatically; the user must only specify the coefficient `eta_ad`.  See Issue #369.   

What do you think, @zhuzh1983 @tomidakn @felker ?

**Comment by zhuzh1983** [comment]
It looks great to me. If we can add the equation on the wiki it could be clearer.

**Comment by pdmullen** [comment]
> It looks great to me. If we can add the equation on the wiki it could be clearer.

In Equation 6D of the Athena++ code paper, however, I believe that $\eta_\mathrm{AD}$ is *not* equal to `<problem>/eta_ad`.  Instead,  maybe we should write the equation as:

$\frac{\partial \mathbf{B}}{\partial t} - \nabla \times \left[\left(\mathbf{v} \times \mathbf{B} \right) - \eta \mathbf{J} - \eta_\mathrm{AD} \\; \mathbf{B} \times \left(\mathbf{J} \times \mathbf{B} \right) \right ] = 0$

where $D = \eta_\mathrm{AD} \lvert \mathbf{B}^2 \rvert \equiv$ the amipolar diffusion coefficient (with units [length]^2/[time]).  

Can someone check me?
