### ISSUE TITLE
Unwanted spiral density waves in parallel sims

### ISSUE THREAD

**Issue by gaturpin** [PrincetonUniversity/athena#370]
Hi, I've been struggling with an issue where I have been seeing some strange density spiral waves originating from the boundaries when running mpi + hdf5 enabled:

<p align="center">
<img src="https://user-images.githubusercontent.com/85227684/120614093-c6660500-c44e-11eb-99d8-e537717ac5c7.png" width="500" height="500">
</p>

This isn't an issue when running the same pgen in serial: (Figs taken at same timestep)
<p align="center">
<img src="https://user-images.githubusercontent.com/85227684/120614484-31afd700-c44f-11eb-9146-dc58e94e81ba.png" width="600" height="600">
</p>

The versions of the modules/libs I am using are:
intel/2017.1,  intelmpi/2017.1,  hdf5-parallel/1.8.18

and my compilation command is (parallel):
`h5pcc  -I/share/apps/centos7/hdf5-parallel/1.8.18/intel/include -O3 -std=c++11 -qopenmp-simd -diag-disable 3180`

The h5pcc wrapper calls:
`mpicc -L/share/apps/centos7/hdf5-parallel/1.8.18/intel/lib /share/apps/centos7/hdf5-parallel/1.8.18/intel/lib/libhdf5_hl.a /share/apps/centos7/hdf5-parallel/1.8.18/intel/lib/libhdf5.a -lz -ldl -lm -Wl,-rpath -Wl,/share/apps/centos7/hdf5-parallel/1.8.18/intel/lib`

I have seen issue #340 which I thought could have been similar, but I've gone through the potential solutions and haven't had any luck.

I think it could related to the meshblocks as when I increase the number of blocks I get an increased number of spirals. Each individual spiral does originate from the corner of each block:
<p align="center">
<img src="https://user-images.githubusercontent.com/85227684/120617703-46da3500-c452-11eb-97cb-93ce673b3777.png" width="600" height="600">
</p>

Any ideas on how I might find the cause of this issue?
Cheers!

**Comment by tomidakn** [comment]
To use Intel Compiler, you need *all* the optimization options provided by configure.py with the `--cxx icpc` option. In particular, do not omit `-ipo` and `-inline-forceinline`, and make sure these options are correctly passed to mpicc. These are essential for successful vectorization.

**Comment by gaturpin** [comment]
Oops sorry, okay great thank you. 

I have been trying to compile with the same options as` --cxx icpc`: 
`h5pcc -I/share/apps/centos7/hdf5-parallel/1.8.18/intel/include -O3 -std=c++11 -ipo -xhost -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180`

But at the end of the compile I am getting:
```
icc: error #10106: Fatal error in /share/apps/intel/compiler/17.0.1/compilers_and_libraries_2017.1.132/linux/bin/intel64/mcpcom, terminated by EMT instruction
icc: error #10014: problem during multi-file optimization compilation (code 1)
make: *** [bin/athena] Error 1
```

From what I have seen this could be an issue with the 2017 intel compiler, so I'll have a chat with support for the cluster I am using about this problem. (I can't just use a later version since the hdf5-parallel libraries I am using are built with and depends on the 2017 version).

Thank you!

**Comment by felker** [comment]
Closing since we have seen similar issues with 2017 versions of ICC that disappeared in later releases.
