### ISSUE TITLE
Viscous diffusion in rotating frame

### ISSUE THREAD

**Issue by ncimerman** [PrincetonUniversity/athena#373]
Hi all,

I was just looking at the implementation of viscosity when using a rotating frame and/or orbital advection in cylindrical coordinates.

When using orbital advection, it seems that before calculating the viscous stress, the system is transformed back to the inertial frame, which makes sense to me.

When using a rotating frame however, I did not find a similar transformation. It is not directly obvious to me that using a constant angular frequency Omega0 would allow one to use the velocities in the rotating frame to calculate the stress, but perhaps I missed something.

I tested the 'disk' pgen with both frames (rotating and inertial) and did not find any notable discrepancies in the evolution of the surface density for a viscosity corresponding to an alpha ~ 0.1. So in case the implementation was missing something, the effect would be small in this situation.

However, I am currently observing some slightly different behaviour between the two frames using another pgen of my own and was wondering whether this might be related to this.

So overall, I just wanted to check whether the implementation of the rotating frame is compatible with viscosity and I have just missed where this is taken into account or made a mistake. Sorry if I did!

Kind regards,
Nicolas

**Comment by tomo-ono** [comment]
When we use the orbital advection, we transform the orbital velocity frame to the inertial frame (Omega0==0) or the rotating frame (Omega0!=0) before calculating the viscous stress. We assume that `v_i` is the velocity field in the inertial frame and `v_r` is in the rotating frame. Then, `w=v_i-v_r` represents the rigid rotation velocity at Omega0. Unless I do some mistakes, there is no viscous stress from `w`. Therefore, I think that we don't have to transform the system from the rotating frame to the inertial frame before calculating the viscous stress.

If you find some differences between results in the inertial frame and the rotating frame, it is probably numeric. They are identical analytically, but there is no guarantee that they are identical numerically. The differences must be subtle. 

If I am wrong, please let me know it.

**Comment by ncimerman** [comment]
Hi,

thanks for the quick response. I just had another look at my calculation and I think I found my mistake. I do now seem to agree that for a rigid rotation with constant Omega0, the Omega0 terms all drop out and effectively one can replace v_i with v_r for calculating the viscous stress.

I realized another difference in the outputs of my non-axisymmetric potential pgen is that they are shifted in phi, but not the way I was expecting.

Is the output given in terms of azimuthal angle of the rotating frame phi = phi0 + Omega0*time?
From my understanding, if Omega0 = 1.0, and I output every 2pi in time, then the two frames should align anyway, but this does not appear to be the case. Could you please confirm what the output coordinates are?

I did another test with the axisymmetric 'disk' pgen, where I added a passive scalar and there densities of the passive tracer agree for outputs every 2pi agree between the two frames, without a shift in phi.

Thus, I will also go back and double check my custom pgen for potential issues.

Thanks very much
Nicolas
