### ISSUE TITLE
Shear flag is set to false for all corner neighbors

### ISSUE THREAD

**Issue by changgoo** [PrincetonUniversity/athena#377]
https://github.com/PrincetonUniversity/athena/blob/4429039d0906ba53cd6637dd753c804762c090a9/src/bvals/bvals_base.cpp#L693-L726

I found that the shear flag is set to false for all corner neighbors. There are corner neighbors across shear-periodic boundaries (across x1). I'm not sure that this is necessary for current shear-periodic boundary conditions for hydro boundary variables. @tomo-ono Could you please confirm this?

Even though it is not necessary to flag it as it is unused, I think it might be good to flag it for any future implementation that relies on `nb.shear` flag to identify the shearing-periodic boundaries. In my case, I'm writing a class for particle-mesh communication derived from CellCenteredBoundaryVariable. There, I need to handle corner neighbor information correctly across x1 boundary.

**Comment by tomo-ono** [comment]
As @changgoo points out, the flag is always false for all corner neighbors and it must be a bug. In fact, the flag works only at boundaries facing on the shear-periodic boundaries. The bug would have no effects on results at present. However, it will be important when we consider the shearing box with SMR/AMR. I will make a PR with modifications of the flag.
