### ISSUE TITLE
Output synchronization: Unable to generate same number of output files for two simulations

### ISSUE THREAD

**Issue by kurtsansom** [PrincetonUniversity/athena#387]
**Prerequisite checklist**

- [X] Did you check that the issue hasn't already been reported?
- [X] Did you check the documentation in the Wiki for an answer?
- [X] Are you running the latest version of Athena++?

**Summary of issue**
When running a (low resolution) simulation the output does not generate even timestep information.

I wrote a custom problem generator that includes a gravity source and want to compare the output with the source enabled and disabled. However the number of output files is not even between the two simulations.

**Steps to reproduce**

- configure: `python configure.py --prob=cme --eos=adiabatic --coord=cylindrical -hdf5 -omp -b --hdf5_path=/home/krs/miniconda3/envs/mhd --nghost 2`
- run two simulations with source on versus off
-  observe number of output files is different between simulations

**Expected outcome**

Number of output files to be the same

**Actual outcome**

Number of generated files is not the same

**Additional comments and/or proposed solution**

output and time settings
```
<output3>
file_type  = hdf5       # Binary data dump
variable   = cons       # variables to be output
dt         = 0.0001     # time increment between outputs
ghost_zones = 1         # include ghost zones

<time>
cfl_number = 0.4 
nlim       = -1    
tlim       = 0.5
start_time = 0.0    
integrator  = vl2       
```

how to get into paraview:
For each set of results:
- load into paraview (XDMF readers)
- extract block
- cleantoGrid
- Calculator to convert to cylindrical coordinates (specific to my output)
coordsX*cos(coordsY)*iHat + coordsX*sin(coordsY)*jHat + coordsZ*kHat

Filter to combine data:
- programmable filter with two inputs
```
in_0 = inputs[0]
in_1 = inputs[1]
output.CellData.append(in_0.CellData["dens"] - in_1.CellData["dens"],
                       'difference')
```

**Version info**
Branched from master ed146acbad3a2bb35770c004266919d32a08faf1

**Comment by felker** [comment]
How many output files and timesteps occur in each case? Sounds like the source term might radically decrease your timestep, leading to more outputs.

**Comment by gonihalevi** [comment]
If your timestep is larger than your output dt (0.0001) in one simulation but not in the other (in your case, in the run without a source term, dt may be > 0.0001), you'll get a different number of files, because in practice the outputs can't happen with a frequency greater than that of the simulation timesteps. Try to increase your output timestep to something greater than the smallest dt in your source-free run.

**Comment by kurtsansom** [comment]
@gonihalevi  I believe that you are correct. when I changed the dt = 0.001, the output amounts were the same, is there a  dt_min setting?

**Comment by gonihalevi** [comment]
@kurtsansom yes, you could set a User-Defined Timestep in your problem generator that just takes the minimum between the CFL-set dt and some constant, in your case. See the wiki page: https://github.com/PrincetonUniversity/athena/wiki/Problem-Generators#user-defined-time-step

**Comment by kurtsansom** [comment]
Thank you @gonihalevi 
 summary: output points occur at `max(solver_timestep, dt)` therefore set `dt` to a value higher than larger than smallest timestep. 

That solves my problem I will close this issue.

**Comment by c-white** [comment]
@kurtsansom I'll just note that the solver timestep is by default never shortened to make the next end of timestep (and output opportunity) exactly match with the next desired output time, except for the very last step in the simulation. That is, the time of the output is generally a little later than you might expect based on the input parameters, by of order half a timestep. For detailed comparisons, it is always useful to check the `Time` file-level attribute in the outputs to see exactly when the output was made.

**Comment by kurtsansom** [comment]
What is the best way to compare two simulations? (sans interpolation in time for a given solution)
Constraining the timestep with a user defined function? or are there better ways to  ensure the comparison is "apples to apples"?

**Comment by c-white** [comment]
@kurtsansom You can probably do something clever with the user-defined timestep by examining `pmb->pmy_mesh->time`, setting a shorter timestep if the next desired output time is imminent. If you only want to compare one file from each run, just run to that point, since the simulation will stop exactly at the `tlim` input parameter.

**Comment by kurtsansom** [comment]
> @kurtsansom yes, you could set a User-Defined Timestep in your problem generator that just takes the minimum between the CFL-set dt and some constant, in your case. See the wiki page: https://github.com/PrincetonUniversity/athena/wiki/Problem-Generators#user-defined-time-step

I was able to do this simple thing in the problem file in the pgen directory:

```cpp
Real SetMinimumTimeStep(MeshBlock *pmb);

...

namespace {
bool enable_user_dt;
Real user_dt;
} // namespace

void Mesh::InitUserMeshData(ParameterInput *pin) {
...
  // enroll user defined timestep
  enable_user_dt = pin->GetOrAddBoolean("problem", "enable_user_dt",false);
  if (enable_user_dt) {
    EnrollUserTimeStepFunction(SetMinimumTimeStep);
  }
...
}

void MeshBlock::ProblemGenerator(ParameterInput *pin) {
...
  if (enable_user_dt) {
    user_dt = pin->GetOrAddReal("problem", "user_dt", 0.01);
  }
...
}

Real SetMinimumTimeStep(MeshBlock *pmb)
{
  return user_dt;
}

```
