### ISSUE TITLE
linwave1d with iso_sound_speed != 1

### ISSUE THREAD

**Issue by chaochinyang** [PrincetonUniversity/athena#391]
**Prerequisite checklist**

Place an X in between the brackets on each line as you complete these checks:
- [X] Did you check that the issue hasn't already been reported?
- [ ] Did you check the documentation in the Wiki for an answer?
- [X] Are you running the latest version of Athena++?

**Summary of issue**
When the input parameter iso_sound_speed is changed, the sound crossing time does not change.

**Steps to reproduce**
Simply change hydro/iso_sound_speed to some value different from one.

**Expected outcome**
When iso_speed_sound = 10, one should see the wave crosses the domain 50 times with time/tlim = 5.

**Actual outcome**
One actually see the wave still crosses the domain 5 times.

**Version info**

- Athena++ version: latest (commit 5261e49)
- Compiler and version: clang++ (Apple clang version 12.0.5)
- Operating system: Mac OS 11.5.2
- Hardware and cluster name (if applicable): MacBook Pro 2020 (Intel)
- External library versions (if applicable):

**Comment by felker** [comment]
@chaochinyang why did you close this?

**Comment by chaochinyang** [comment]
I didn’t notice that iso_sound_speed does not control the sound speed when eos=adiabatic.

It would be nice if it did, though, which could be a feature request.

Sincerely,
Chao-Chin
 <http://unlv.edu/>	
Chao-Chin Yang
Assistant Research Professor
Department of Physics and Astronomy
University of Nevada, Las Vegas
***@***.*** ***@***.***>
Office: 702-895-0961
Web <http://www.physics.unlv.edu/~ccyang/>
