### ISSUE TITLE
linwave: initial conditions do not scale with resolution

### ISSUE THREAD

**Issue by chaochinyang** [PrincetonUniversity/athena#392]
**Prerequisite checklist**

Place an X in between the brackets on each line as you complete these checks:
- [X] Did you check that the issue hasn't already been reported?
- [ ] Did you check the documentation in the Wiki for an answer?
- [X] Are you running the latest version of Athena++?

**Summary of issue**

The initial conditions by `pgen/linear_wave.cpp` continue to show staircases at high resolutions.

**Steps to reproduce**

Simply vary `mesh/nx1` in `athinput.linwave1d`.

**Expected outcome**

The initial data approaches a continuous function as `nx1` increases.

**Actual outcome**

The initial data still shows staircases at high resolutions.
![linwave](https://user-images.githubusercontent.com/11709830/133907028-cef36c45-8627-46b5-8f9c-7f071f8a5d6c.png)

**Version info**

- Athena++ version: latest (commit 5261e49)
- Compiler and version: Clang++ (Apple clang version 12.0.5)
- Operating system: macOS 11.5.2
- Hardware and cluster name (if applicable): MacBook Pro 2020 (Intel)
- External library versions (if applicable):

**Comment by c-white** [comment]
This appears to be a precision problem with the outputs. Can you repeat the test with `-hdf5 -h5double` and `output2/file_type=hdf5` and confirm that the stairstepping vanishes?

**Comment by chaochinyang** [comment]
Good catch!  Indeed the problem was that VTKs cannot hold high precisions, instead of the data itself.  With HDF5,
![linwave](https://user-images.githubusercontent.com/11709830/133909725-4bbdc661-f277-4732-9de7-9144ed20ea7f.png)
