### ISSUE TITLE
plot_slice.py issues

### ISSUE THREAD

**Issue by kurtsansom** [PrincetonUniversity/athena#393]
**Prerequisite checklist**

Place an X in between the brackets on each line as you complete these checks:
- [X] Did you check that the issue hasn't already been reported?
- [X] Did you check the documentation in the Wiki for an answer?
- [X] Are you running the latest version of Athena++?

**Summary of issue**
athdf reader appears to read as byte objects rather than strings objects.

when reading a file in cylindrical coordinates It returns a warning, `warnings.warn('Coordinates not recognized; results may be misleading')` but when I print the string it reveals the string read from the file is a byte string.
 e.g. b'cylindrical' which when compared with 'cylindrical' returns false. 

**Steps to reproduce**

Configuration:

```
configure = --prob=cme --prob=cme --eos=adiabatic --coord=cylindrical -hdf5 -omp -b --hdf5_path=/home/krs/miniconda3/envs/mhd
```

```
../athena/vis/python/plot_slice.py -d 3 --colormap plasma --stream Bcc  solar_wind.out3.00001.athdf dens output/slice.png
```

**Actual outcome**

**Additional comments and/or proposed solution**

**Version info**
git tag: 5261e49

Conda environment:
[conda_env.txt](https://github.com/PrincetonUniversity/athena/files/7204690/conda_env.txt)

**Comment by c-white** [comment]
This seems like one of those things Python3 incomprehensibly broke. Apparently either all other users are like me and still use Python2, or no one else uses the plotting scripts...

Can you checkout the branch `plotting_fix` to make sure it fixes the problem?

**Comment by felker** [comment]
Actually, I am pretty sure this is due to changes in `h5py` with the release of their 3.x versions:
- https://docs.h5py.org/en/latest/strings.html
- https://github.com/tensorflow/tensorflow/issues/44467

**Comment by msbc** [comment]
I feel like we should include these plotting scripts in regression testing. 

Also, to add onto @felker 's point: I'm pretty sure I successfully used `plot_slice.py` in the past with Python3. While I don't really use the scripts in `vis/python`, I've refused to use Python2 for several years now and I'd be surprised if I hadn't used `plot_slice.py` in that time.

**Comment by kurtsansom** [comment]
@c-white  why not use `utf-8`?

**Comment by kurtsansom** [comment]
@c-white the branch works for me when doing the basic plot. 

Unrelated issue that now pops up when I exposed num_ghost into the script, I get an error when trying to plot with `--stream` enabled. e.g. `ValueError: 'x' values must be equally spaced` not sure yet if its related to the num_ghosts or something else.

**Comment by kurtsansom** [comment]
I created an WIP PR that I incorporates some fixes plus other stuff I needed to get it working for me.

**Comment by felker** [comment]
I wonder if the decoding error in `h5py` is also responsible for https://github.com/PrincetonUniversity/athena/discussions/383

**Comment by arka378** [comment]
I have encountered this issue with the default plotting files before. I usually fix them by looking into the file and finding the places where the strings are being read. Then you essentially use `.decode('utf-8')` method of the string class in Python to cast them into "usual" strings -- this will render the comparison to `True`. Essentially:

`>>> a, b = b'cylindrical', 'cylindrical'`
`>>> a == b`
`>>> False`

But:

`>>> a.decode('utf-8') == b`
`>>> True`
