### ISSUE TITLE
Possiblly wrong code in EquationOfState::ApplyPrimitiveFloors

### ISSUE THREAD

**Issue by luminoctum** [PrincetonUniversity/athena#395]
**Prerequisite checklist**

Place an X in between the brackets on each line as you complete these checks:
- [x] Did you check that the issue hasn't already been reported?
- [x] Did you check the documentation in the Wiki for an answer?
- [x] Are you running the latest version of Athena++?

**Summary of issue**

**Steps to reproduce**

This section may consist of:
- `configure.py` configuration script options
- `athinput.prob` file and/or command line options

You may want to include small snippets of Athena++ source code to describe the problem in more detail:
```c++
// If it is helpful, you may paste C++ source here
```
**Expected outcome**

```
# Terminal output may be pasted here
```
**Actual outcome**

You may attach a plot here, if it is appropriate.

**Additional comments and/or proposed solution**

**Version info**

- Athena++ version:
- Compiler and version:
- Operating system:
- Hardware and cluster name (if applicable):
- External library versions (if applicable):

**Comment by luminoctum** [comment]
Hi,

Currently, this function is written as:

...
void EquationOfState::ApplyPrimitiveFloors(AthenaArray<Real> &prim, int k, int j, int i) {
  Real& w_d  = prim(IDN,i);
  Real& w_p  = prim(IPR,I);
...

in src/eos/adibatic_hydro.cpp

Should it be

...
void EquationOfState::ApplyPrimitiveFloors(AthenaArray<Real> &prim, int k, int j, int i) {
  Real& w_d  = prim(IDN,**k,j**,i);
  Real& w_p  = prim(IPR,**k,j**,I);
...

?

Thanks,
Cheng

**Comment by pgrete** [comment]
Hi Cheng,

the current code should be correct as it acts on the reconstructed left and right states states in the flux calculation.
Those are pencils (in `i`-direction) so the `prim` array does not carry `k` or `j` indices in that function.

Cheers,

Philipp

**Comment by luminoctum** [comment]
Thanks! The API may be confusing if it is written in this way. But glad to know the code is correct.

**Comment by felker** [comment]
I agree it is confusing, partly because it changed in the past from operating on 4D `prim` array input. 

We also need the other indices as input, in case there is a spatial dependence in the flooring function. 

We could rename the input array as `prim_i` or `prim_x1`, and add a comment.
