### ISSUE TITLE
Write generated configuration to file

### ISSUE THREAD

**Issue by kurtsansom** [PrincetonUniversity/athena#396]
Currently the configuration script appears to print the configuration at the end to summarize the configuration. 

It would be nice to write to a file or store in a cache somehow, so that after something has been configured it is easy to review what was configured especially if there are defaults chosen but are not explicitly put in the command line, e.g. the flux is set depending on the options though absent at the command line. 

possible solution:
- write the configuration `state` to file, and add `--print` option to the configure script that looks for the file, loads and prints it, then replace the print statements  at the end of the configuration file printing the configuration state.

**Comment by felker** [comment]
You can always recover the configuration with `./athena -h`. I would suggest redirecting that command's output to a file, if you need it for future reference but arent keeping the binary around.
