### ISSUE TITLE
Incorrect running index for face-centered variable 

### ISSUE THREAD

**Issue by changgoo** [PrincetonUniversity/athena#403]
I found that in `FaceCenteredBoundaryVariable::OutflowOuterX3`, the running index for `x2f` didn't go all the way to `ju+1`.

So, the following line 

https://github.com/PrincetonUniversity/athena/blob/5261e495b2f69f9c57d9899619d85ad419217fe6/src/bvals/fc/outflow_fc.cpp#L210

must be corrected to

```
    for (int j=jl; j<=ju+1; ++j) {
```

**Comment by felker** [comment]
Nice catch!
