### ISSUE TITLE
Wrong density used for relativistic passive scalar prolongation

### ISSUE THREAD

**Issue by c-white** [PrincetonUniversity/athena#419]
Just as a sanity check, in `BoundaryValues::ProlongateGhostCells`, the line

https://github.com/PrincetonUniversity/athena/blob/71c5bab167499cff450d0486a5465b51f92031a9/src/bvals/bvals_refine.cpp#L566-L567

should have `ph->u` rather than `ph->w`, right? It would only show up in multidimensional, relativistic, mesh-refinement, passive-scalar calculations with nontrivial Lorentz factors.

**Comment by felker** [comment]
Looks like a typo to me.

**Comment by pdmullen** [comment]
I just want to confirm that this is unrelated to #365. 

@c-white ...this only affects GR/SR? Is that because this function is called only after `u` and `w` are synced in Newtonian (M)HD?

**Comment by c-white** [comment]
@pdmullen Yes, `u` and `w` are synced. It's just that the "real" conversion between `r` and `s` is &gamma;&rho;, not &rho;.
