### ISSUE TITLE
"hanging" simulations 

### ISSUE THREAD

**Issue by nchoksi4456** [PrincetonUniversity/athena#430]
**Summary of issue**

My simulation "hangs" at a seemingly random point -- it suddenly starts to take inordinately long to run (see the plot below). The issue only crops up for certain choices of resolution. I'm running pure hydro to study planet-disk interactions. Static mesh refinement is included near the planet. 

Any ideas people have for debugging this issue would be appreciated (and sorry if this ends up having a simple solution).

**Steps to reproduce**

My problem generator can be found [here](http://ugastro.berkeley.edu/~nchoksi/zhu_disk_original.cpp) and my input file [here](http://ugastro.berkeley.edu/~nchoksi/zhu_input_h3.500_qth_0.1).

**Actual outcome**
The top panel of the plot below shows the simulation timestep for two different runs. The pink curve is a lower resolution model that runs to completion without a hitch. The black curve is a higher resolution (in the static mesh refinement region) model.  In both runs, the simulation timestep gradually decreases as the simulation progresses.

The bottom panel of the plot shows the actual walltime between each 0.01 of simulation time. For a while this walltime increases commensurately with the decreasing timestep. But then at t ~ 35, the simulation "hangs" -- the walltime between successive 0.01 intervals of simulation time increases drastically, despite the fact that the simulation timestep is behaving reasonably. So the code must be spending a lot of time on something else. Not sure what.

<img width="301" alt="hanging" src="https://user-images.githubusercontent.com/25126947/157285278-5629deb5-204b-4d11-b259-d5999d97e025.png">

The problematic/hanging simulations finish running without a hitch if I restart them from a checkpoint. 

Also, I've checked that this is not a one-off issue. I ran the setup a few times using different nodes (though all on the same cluster). 

Thanks!

**Version info**

- Athena++ version: v21.0
- Compiler and version:  gcc (GCC) 6.3.0
- Operating system:  Scientific Linux 7
- Hardware and cluster name (if applicable):
- External library versions (if applicable):

**Comment by felker** [comment]
What is your full configure + compilation command? Just to be clear, you are doing this on a single CPU core?

When you Ctrl-C SIGINT the code, does it tell you what function it was in when the signal was caught? Have you tried using gprof or even just print statements to see where it gets stuck?

**Comment by nchoksi4456** [comment]
> What is your full configure + compilation command?

`python configure.py --prob zhu_disk_original --coord spherical_polar --eos isothermal -mpi -hdf5`


>  Just to be clear, you are doing this on a single CPU core?

I'm running across a few hundred cores (on Berkeley's savio cluster, as Chris noted).


> One hypothesis is that this is a small memory leak. If Savio doesn't have tools to report on memory usage automatically, it might be possible to periodically ssh into a compute node while the job is running to check how much memory is being used.

Here's some data from the job, taken while it was still running but after it has reached the "hanging" point. I don't see anything obviously wrong, but I'm no expert so any thoughts would be welcome.

<img width="538" alt="Screen Shot 2022-03-09 at 8 28 56 PM" src="https://user-images.githubusercontent.com/25126947/157589930-70f54c52-c20a-45ad-bc1e-e016b07fef18.png">

And here is what I get when I run "top" on one of the compute nodes on which the job is running:

<img width="589" alt="Screen Shot 2022-03-09 at 8 36 55 PM" src="https://user-images.githubusercontent.com/25126947/157590683-cb4d89ef-65cd-42d5-b8a0-3325543615f2.png">

**Comment by tomo-ono** [comment]
@nchoksi4456  I have had similar problems. When a planet is massive (>~ MJ) and the resolution is high, 3D simulations are easily to hang in my cases. As long as I checked, density and/or pressure gets negative then in some cells due to the strong planet gravity. 
Please check below
1. Is the planet mass massive in your simulations?
2. Does a history output file shows `NAN` value just before the crash? 

If your problem is the same one as mine, I can show some solutions to you. However, those are not fundamental unfortunately.
1. Adopt higher resolution in the x2 direction (polar angle) compared  to one in the x3 direction (azimuthal angle). 
2. Use the Minmod limiter to density and pressure instead of the van Leer limiter. 
If you try the second, you need to understand the code and give changes.

**Comment by zhuzh1983** [comment]
@tomo-ono , could this be related to the disk noise problem we had with 3rd order reconstruction? @tomo-ono what is your new email address? I have some questions on the limiter which is not quite related to this. So I want to send you emails. But your princeton email bounces back.

**Comment by tomo-ono** [comment]
@zhuzh1983 I will send e-mail to you.
