### ISSUE TITLE
Small bug in specifying uov output

### ISSUE THREAD

**Issue by zunyibrt** [PrincetonUniversity/athena#436]
Hello,
It seems after commit 33ad4553d023ffbf1006aba6ec67c8d68e0b8d51, just specifying uov as an output variable no longer works (throws a variable not implemented error), which probably wasn't the intended effect since the wiki still shows this as an example. Instead one is forced to cherry pick the user output variables (so uov0 works). This is easily reproducible with a fresh copy of the current code and running the linear wave test case while trying to output the variable uov. There is also a typo in the changes (line 688) so uov0 works but user_out_var0 does not. abbr_name is repeated twice but I think the intention was for the second condition to be ContainVariable(output_params.variable, full_name).

**Comment by kahoooo** [comment]
Sorry about not noticing and working on this issue earlier. This is indeed unintended. Thanks for pointing it out.
Working on this now.
