### ISSUE TITLE
`athena_read.py` produces corrugated spherical-polar `x2v` coordinates due to float precision at high resolution

### ISSUE THREAD

**Issue by astroboylrx** [PrincetonUniversity/athena#498]
**Prerequisite checklist**

Place an X in between the brackets on each line as you complete these checks:
- [X] Did you check that the issue hasn't already been reported?
- [X] Did you check the documentation in the Wiki for an answer?
- [X] Are you running the latest version of Athena++?

**Summary of issue**

When reading data from a spherical-polar simulation with SMR, `athdf` in `athena_read.py` produces corrugated `x2v` coordinates. I found this when `scipy.interpolate.RegularGridInterpolator` reported that `The points in dimension 1 must be strictly ascending or descending`.

Specifically, `data[xf] = np.linspace(xmin, xmax, nx + 1, dtype=dtype)` at [here](https://github.com/PrincetonUniversity/athena/blob/fe6561b10e0abae60c75b60bdc0039119941d1f0/vis/python/athena_read.py#L648) and `data[xv] = np.empty(nx, dtype=dtype)` ([here](https://github.com/PrincetonUniversity/athena/blob/fe6561b10e0abae60c75b60bdc0039119941d1f0/vis/python/athena_read.py#L656)) make the face/center coordinates inherit the `dtype` of the first variable ([here](https://github.com/PrincetonUniversity/athena/blob/fe6561b10e0abae60c75b60bdc0039119941d1f0/vis/python/athena_read.py#L407)), which makes the `center_func` (here) unable to produce correct center coordinates as the algorithm is sensitive to floating precision.

The picture below shows that the `x2v` (288 coordinates between (xmin, xmax) = (1.5271630734205246, 1.614429548382759)) is corrugated, where the differences between consecutive coordinates sometimes become negative:
![Figure 8](https://github.com/PrincetonUniversity/athena/assets/3999966/292767ac-b486-4448-9449-b6ecf6511341)

Since the keyword `dtype` also controls the precision of simulation data, it is not desired to specify `dtype=np.float64` when calling `athdf`. 

---
**A quick easy fix** would be removing all the `dtype=dtype` in [this for loop](https://github.com/PrincetonUniversity/athena/blob/fe6561b10e0abae60c75b60bdc0039119941d1f0/vis/python/athena_read.py#L615). So the coordinates will fall back to the default `np.float64` precision. 

**Version info**

- Athena++ version: commit [fe6561b](https://github.com/PrincetonUniversity/athena/commit/fe6561b10e0abae60c75b60bdc0039119941d1f0)
- Compiler and version: irrelevant
- Operating system: irrelevant
- Hardware and cluster name (if applicable):
- External library versions (if applicable):

**Comment by c-white** [comment]
This issue had been previously reported and addressed with another user, but in private. For posterity, here is an excerpt from that exchange:

> Quick fix: add `dtype=np.float64` to your athena_read.athdf call. This will double the memory footprint of your script, but it will fix the grid.
> 
> Details:
> 
> While the code calculates everything in double precision (unless you tell it otherwise), outputs are single precision (again, unless told otherwise). This is usually a good thing, since analysis doesn't require 17 digits of precision, and hard drive space can be limited.
> 
> At the same time, mesh refinement creates an interesting problem. Users want a uniform grid, by default cast to the highest refinement level. But there's no guarantee that a fine cell in the uniform grid has coordinates that exist anywhere in the mesh refinement grid. So in creating a uniform grid, the script must be able to create new x1f, x1v, etc. arrays given only endpoints and the desired number of cells. And it does this, the same way Athena itself does it.
> 
> However, in the athena_read.athdf script, this procedure is done at the same precision as the data dump. In particular, the correct formula for the volume center theta_c of a cell with faces at theta_m and theta_p is
> 
> ```
> theta_c = (sin(theta_p) - theta_p * cos(theta_p) - sin(theta_m) + theta_m * cos(theta_m)) / (cos(theta_m) - cos(theta_p))
> ```
> 
> And for your very fine resolution near pi/2, single precision is not sufficient for this formula to work, and there are catastrophic cancellation errors.
> 
> An alternate quick fix then is to replace the x2v array given the x2f array (which is correct):
> 
> ```
> data = athena_read.athdf(filename, ...)
> thf = data['x2f'].astype(np.float64)
> data['x2v'] = np.diff(thf * np.cos(thf) - np.sin(thf)) / np.diff(np.cos(thf))
> ```
> 
> I might consider forcing this calculation to always be in double precision in a future update to the code. As far as I know, no one has ever encountered this before.

I'll work on making a more permanent fix, given that this is now affecting multiple people.

**Comment by c-white** [comment]
The new fix about to be merged in removes the `dtype`s as suggested above.

For the specific numbers above, before the fix, the minimum and maximum of `np.diff(data['x2v'])` were `-0.0002707243` and `0.0008716583`. Now they are `0.00030297040587590196` and `0.00030303001311127176`.

There is a chance that some users will be adversely affected by the new double-precision coordinates increasing the footprints of their own derived arrays. That is, `numpy` will promote the output of a mixed-precision calculation to double, so scripts that were near to exceeding memory limits might do so now without manually forcing arrays back to `dtype=np.float32`.
