### ISSUE TITLE
Fix convergence errors on AWS EC2 Graviton instances

### ISSUE THREAD

**Issue by felker** [PrincetonUniversity/athena#509]
Reported by Jianjun Xu.

When using Graviton 2 (c6g.xlarge) to run Athena++, the code will fail to converge (linear wave? details missing) using the default `-O3` compiler option. But changing to `-O2` fixed the convergence.

- [ ] Also test on Graviton 3 (cg7) instance 

Here is the script used to install Athena++ on ParallelCluster:  https://github.com/aws-samples/aws-research-workshops/blob/mainline/notebooks/parallelcluster/scripts/pcluster_post_install-6g.sh

**Comment by felker** [comment]
@jxuamazon

**Comment by tomidakn** [comment]
If I understand correctly, he said -O3 converges but the other configurations fail. I suspect that -O2 fails to unroll some functions and interfere vectorization with #pragma omp simd. (-O0 should work.) If this is the case, it is expected, but maybe it should be better documented.

**Comment by jxuamazon** [comment]
@tomidakn sorry, I remembered incorrectly when I talked to you about this.  -O3 does not converge , but -O2 does.  
@felker - I used Orszag-tan vortex test with 512x512 and 256x256 resolution. with -O3, the time step kept getting smaller and the program will run for a long time.  I plan to run some more test on graviton 3 in the coming weeks.

**Comment by jxuamazon** [comment]
Tested this on C7g,  the issue no longer exists.   We can close this issue.

**Comment by jxuamazon** [comment]
tested on graviton3 c7g instance. the issue no longer exists.
