### ISSUE TITLE
Resurrect Princeton Jenkins server

### ISSUE THREAD

**Issue by felker** [PrincetonUniversity/athena#515]
Sometime after I left Princeton University, the Jenkins instance running on Princeton servers and launching our CI jobs on up to 4x Intel Broadwell nodes of the PICSciE Perseus cluster (RIP) stopped working. Not actually sure when the last Jenkins job ran--- late 2019 or 2020?

I believe @changgoo cloned the Jenkins server instance for the TIGRESS project on a different repo. If so, it would be simple to clone it again and reinstate it for Athena++ under someone's Princeton Research Computing account; we would just need to modify the webhook here once that is complete. 

It would be great to bring this up before merging #492 or #496. 

- [x] Update https://github.com/PrincetonUniversity/athena/blob/master/tst/ci/jenkins/run_jenkins_perseus.sh to work with a new cluster (`stellar`?), new compiler and MPI/HDF5/etc. versions, and add new tests
- [ ] Is there a way to configure the webhook to update a build log as it is running on GitHub Actions or somewhere that is visible to people without Princeton computing accounts?
- Or consider a different Jenkins or non-Jenkins CI host?

**Comment by changgoo** [comment]
I will look into this. Can you give me admin access to the repo so that I can change the deploy key and other settings if needed?

**Comment by tomidakn** [comment]
@changgoo I've promoted you.

**Comment by changgoo** [comment]
Manual jenkins run result using script added by #517 

```
./vis/python/plot_slice.py:223:27: E231 missing whitespace after ','
./vis/python/plot_slice.py:223:29: E231 missing whitespace after ','
./vis/python/plot_slice.py:223:31: E231 missing whitespace after ','
./vis/python/plot_slice.py:240:25: E128 continuation line under-indented for visual indent
./vis/python/plot_slice.py:243:25: E128 continuation line under-indented for visual indent
./tst/regression/scripts/tests/mhd/mhd_carbuncle.py:29:13: E128 continuation line under-indented for visual indent
./tst/regression/scripts/tests/mhd/mhd_carbuncle.py:30:13: E128 continuation line under-indented for visual indent
./tst/regression/scripts/tests/mhd/mhd_carbuncle.py:31:13: E128 continuation line under-indented for visual indent
```

**Comment by changgoo** [comment]
@felker @jmstone @tomidakn @c-white Please let me know if you want to receive Jenkins build results via email?

**Comment by changgoo** [comment]
I'm testing PR trigger #518

It seems that the trigger works. The trigger statement on PR is `retest this on stellar`. As I added all admin members to the Jenkins configuration as well, I assume that admin's comment including the trigger statement will trigger Jenkins build.

**Comment by felker** [comment]
Wow, thanks for doing this so quickly @changgoo! Yes please add me to email notifications, for now at least.

**Comment by changgoo** [comment]
Added your email for the build failure with the full build log attached.
