### ISSUE TITLE
athena_read allocates unnecessarily large amount of memory

### ISSUE THREAD

**Issue by dgagnier** [PrincetonUniversity/athena#586]
**Summary of issue**
 athena_read allocates unnecessarily large amount of memory for each quantity, rendering file reading unnecessarily slow or even imposible.  

For example, selecting a region containing blocks at root level, while the maximum refinement level is 7, yields `Unable to allocate 256. GiB for an array with shape (4096, 4096, 4096) and data type float32`, whatever the size of the selected region.

**Steps to reproduce**
Using athena_read without specifying  `level`  (default), or with level > 0.

**Additional comments and/or proposed solution**
In athena_read.py, from line 770:
```
              for q, dataset, index in zip(quantities, quantity_datasets,
                                             quantity_indices):
                    block_data = f[dataset][index, block_num, :]
                    if s > 1:
                        if nx1 > 1:
                            block_data = np.repeat(block_data, s, axis=2)
                        if nx2 > 1:
                            block_data = np.repeat(block_data, s, axis=1)
                        if nx3 > 1:
                            block_data = np.repeat(block_data, s, axis=0)
                    data[q][kl_d:ku_d, jl_d:ju_d, il_d:iu_d] = block_data[kl_s:ku_s,
                                                                          jl_s:ju_s,
                                                                          il_s:iu_s]
```

This allocates an array of size (  2^s  nx1, 2^s nx2, 2^s nx3). Selecting a region containing blocks at root level, while the maximum refinement level is 7 thus allocates  an array with shape  (4096, 4096, 4096), whatever the size of the selected region (even if the size is zero).

**Proposed fix**:  selecting block_data's source indices during np.repeat (instead of after), i.e.

  ```
              for q, dataset, index in zip(quantities, quantity_datasets,
                                             quantity_indices):
                    block_data = f[dataset][index, block_num, :]
                    if s > 1:
                        if nx1 > 1:
                            block_data = np.repeat(block_data, s, axis=2)[:,:,il_s:iu_s]
                        if nx2 > 1:
                            block_data = np.repeat(block_data, s, axis=1)[:,jl_s:ju_s,:]
                        if nx3 > 1:
                            block_data = np.repeat(block_data, s, axis=0)[kl_s:ku_s,:,:]
                        data[q][kl_d:ku_d, jl_d:ju_d, il_d:iu_d] = block_data
                    else:
                        data[q][kl_d:ku_d, jl_d:ju_d, il_d:iu_d] = block_data[kl_s:ku_s,jl_s:ju_s,il_s:iu_s]
```

**Comment by c-white** [comment]
This looks like a reasonable change that will strictly improve things. Would you like to make a pull request?
