### ISSUE TITLE
Segmentation fault with shearing box and multiple meshblocks

### ISSUE THREAD

**Issue by chaochinyang** [PrincetonUniversity/athena#594]
**Summary of issue**
Segmentation fault occurs when running the input file `inputs/mhd/athinput.hgb` with multiple meshblocks.

**Steps to reproduce**
```
./configure.py -b --prob=hgb --eos=isothermal -debug
make clean; make
cd [some working directory]
~/athena/bin/athena -i ~/athena/inputs/mhd/athinput.hgb meshblock/nx1=16 meshblock/nx2=12 meshblock/nx1=16
```
and the segmentation fault results.

This error occurs in function `CellCenteredBoundaryVariable::SetFluxBoundarySameLevel()` of `src/bvals/cc/flux_correction_cc.cpp` at Line 224
```
          shear_var_flx_[1](nn,k,j) = buf[p++];
```
In this case, `shear_var_flx_[1]` has not been allocated with a `NewAthenaArray` because `pbval_->is_shear[1]` is `false`.

**Additional comments and/or proposed solution**
This issue started since commit 811ea3c.

**Version info**

- Athena++ version: commit 44981d3825
- Compiler and version: Apple clang-1500.3.9.4 and MacPorts gcc13 13.2.0_4+stdlib_flag
- Operating system: macOS Sonoma 14.5
- Hardware and cluster name (if applicable): Apple Silicon M2 Max
- External library versions (if applicable):

**Comment by felker** [comment]
Thanks for the report; unfortunate that this was not caught before the release. 

I can reproduce this, and confirm that the seg fault is avoided in the parent commit. Fix incoming
